#!/bin/bash

export USER='pi'
 
eval cd ~$USER
 
# Check state
case "$1" in
  start)
    su $USER -c '/usr/bin/vncserver :1 -geometry 1280x720 -depth 24'
    echo "Starting vncserver for $USER"
  ;;
  stop)
    pkill Xtightvnc
    echo "vncserver stopped"
  ;;
  *)
    echo "Usage: /etc/init.d/vncboot {start|stop}"
    exit 1
  ;;
esac
 
exit 0
